# Generated by Django 5.2.11 on 2026-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='dough_type',
            new_name='dough_thickness',
        ),
    ]
